command:
  - "python"
  - "app.py"

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "database"
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase-url"
  - name: NWS_USER_AGENT
    value: "(weather_app, you@example.com)"
  - name: EMBEDDING_MODEL_NAME
    value: "sentence-transformers/all-MiniLM-L6-v2"
  - name: MODEL_CACHE_PATH
    value: "/Volumes/hv_external_catalog/watchlist_schema/ml_models"
